allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  esbuild: true
  protobufjs: true
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - core-js
  - esbuild
  - protobufjs
