/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as FilesImport } from './routes/files'
import { Route as EnginesImport } from './routes/engines'
import { Route as AccountsImport } from './routes/accounts'
import { Route as IndexImport } from './routes/index'
import { Route as DatabasesIndexImport } from './routes/databases/index'
import { Route as DatabasesDatabaseIdImport } from './routes/databases/$databaseId'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const FilesRoute = FilesImport.update({
  path: '/files',
  getParentRoute: () => rootRoute,
} as any)

const EnginesRoute = EnginesImport.update({
  path: '/engines',
  getParentRoute: () => rootRoute,
} as any)

const AccountsRoute = AccountsImport.update({
  path: '/accounts',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DatabasesIndexRoute = DatabasesIndexImport.update({
  path: '/databases/',
  getParentRoute: () => rootRoute,
} as any)

const DatabasesDatabaseIdRoute = DatabasesDatabaseIdImport.update({
  path: '/databases/$databaseId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/accounts': {
      preLoaderRoute: typeof AccountsImport
      parentRoute: typeof rootRoute
    }
    '/engines': {
      preLoaderRoute: typeof EnginesImport
      parentRoute: typeof rootRoute
    }
    '/files': {
      preLoaderRoute: typeof FilesImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/databases/$databaseId': {
      preLoaderRoute: typeof DatabasesDatabaseIdImport
      parentRoute: typeof rootRoute
    }
    '/databases/': {
      preLoaderRoute: typeof DatabasesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AccountsRoute,
  EnginesRoute,
  FilesRoute,
  SettingsRoute,
  DatabasesDatabaseIdRoute,
  DatabasesIndexRoute,
])

/* prettier-ignore-end */
